// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9_pSej2C0AFbPbK8KijJONdDMaDGGRrg',
    appId: '1:354327007305:web:4b0c86cd051ab90a73af98',
    messagingSenderId: '354327007305',
    projectId: 'imageupload-2e13f',
    authDomain: 'imageupload-2e13f.firebaseapp.com',
    storageBucket: 'imageupload-2e13f.appspot.com',
    measurementId: 'G-2GHEY5YMP7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6-k_NvdKWz9DPZK0XW-bFaXWnQQmeb7Y',
    appId: '1:354327007305:android:dc3a762f052d260273af98',
    messagingSenderId: '354327007305',
    projectId: 'imageupload-2e13f',
    storageBucket: 'imageupload-2e13f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3wedCe9fdZhPH_6vxcsvXzpuTqi91rPM',
    appId: '1:354327007305:ios:9244ebe07fb4b81e73af98',
    messagingSenderId: '354327007305',
    projectId: 'imageupload-2e13f',
    storageBucket: 'imageupload-2e13f.appspot.com',
    iosBundleId: 'com.example.imageUpload',
  );
}
